#!/usr/bin/env python3
"""
3-way comparison: Spike #17.1 (SlidingWindow) vs #17.1.5 (StreamingEOU 160ms) vs #17.2 (whisper.cpp).
Reads CSVs from each spike's results directory, produces COMPARISON.md.
"""
import csv, json, os, sys
from pathlib import Path

SPIKE_ROOT = Path(__file__).parent.parent
RESULTS_17_1   = SPIKE_ROOT.parent / "Spike17.1_ParakeetFeasibility" / "results"
RESULTS_17_1_5 = SPIKE_ROOT.parent / "Spike17.1.5_StreamingEOU" / "results"
RESULTS_17_2   = SPIKE_ROOT / "results"
BOOTSTRAP_17_2 = RESULTS_17_2 / "bootstrap_small.json"

FIXTURE_MAP = {
    # 17.2 fixture base -> (17.1 name guess, 17.1.5 name guess)
    "alternating_pods":  ("alternating_pods",  "alternating_pods_160ms"),
    "quiet_speech_pods": ("quiet_speech_pods",  "quiet_speech_pods_160ms"),
    "cafe_noise_pods":   ("cafe_noise_pods",    "cafe_noise_pods_160ms"),
    "silence_only_pods": ("silence_only_pods",  "silence_only_pods_160ms"),
    "distractors_pods":  ("distractors_pods",   "distractors_pods_160ms"),
}


def read_csv(path):
    if not path.exists():
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def p95(vals):
    if not vals: return None
    s = sorted(float(v) for v in vals)
    return s[int(len(s) * 0.95)]


def analyze(rows, fixture_17_2=None):
    if not rows:
        return {"c4": None, "c5_p95": None, "c8_detected": None, "c9_median": None, "n_events": 0}
    gaps = [float(r["gap_from_previous_ms"]) for r in rows[1:] if r.get("gap_from_previous_ms")]
    confs = [float(r["confidence"]) for r in rows if r.get("confidence") and float(r["confidence"]) >= 0]
    confs_s = sorted(confs)
    c9 = confs_s[len(confs_s)//2] if confs_s else None
    return {
        "c4": None,  # needs bootstrap for 17.2; not available in CSVs for 17.1/17.1.5
        "c5_p95": p95(gaps),
        "c9_median": c9,
        "n_events": len(rows),
    }


def load_c4_17_2():
    if BOOTSTRAP_17_2.exists():
        with open(BOOTSTRAP_17_2) as f:
            d = json.load(f)
        return d.get("c4FirstTokenMs")
    return None


lines = ["# Spike 17.x 3-Way Comparison\n",
         "Generated by tools/compare_to_17_x.py\n",
         "| Fixture | Metric | #17.1 SlidingWindow | #17.1.5 StreamingEOU 160ms | #17.2 whisper-small |",
         "|---------|--------|---------------------|---------------------------|---------------------|"]

c4_17_2 = load_c4_17_2()

for fixture_17_2, (f171, f171_5) in FIXTURE_MAP.items():
    rows_171   = read_csv(RESULTS_17_1   / f"{f171}.csv")
    rows_171_5 = read_csv(RESULTS_17_1_5 / f"{f171_5}.csv")
    rows_172   = read_csv(RESULTS_17_2   / f"{fixture_17_2}_small.csv")

    a171   = analyze(rows_171)
    a171_5 = analyze(rows_171_5)
    a172   = analyze(rows_172)

    def fmt(v, unit="ms"):
        return f"{v:.0f} {unit}" if v is not None else "N/A"

    lines.append(f"| **{fixture_17_2}** | C5 p95 gap | {fmt(a171['c5_p95'])} | {fmt(a171_5['c5_p95'])} | {fmt(a172['c5_p95'])} |")
    lines.append(f"| | C9 median conf | {fmt(a171['c9_median'], '')} | {fmt(a171_5['c9_median'], '')} | {fmt(a172['c9_median'], '')} |")
    lines.append(f"| | N events | {a171['n_events']} | {a171_5['n_events']} | {a172['n_events']} |")

lines.append("")
lines.append(f"**C4 first-token latency (#17.2 whisper-small, from bootstrap):** {c4_17_2:.0f} ms" if c4_17_2 else "**C4:** N/A (bootstrap not run)")
lines.append("")
lines.append("_Prior spike C4: #17.1 ~3500ms (SlidingWindow batch), #17.1.5 ~2336ms (loopback cache warmup)_")

out = SPIKE_ROOT / "COMPARISON.md"
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written: {out}")
